function [K1Top] = PollardTractionIntegrationVerticalCrackK(tnFunc, c, mu, nu, z, zmid, Precomp)
% PollardTractionIntegrationVerticalCrackK Calculates mode I stress intensity 
% factor at crack tips using Townsend and Pollard's (2018) method
%
% This function calculates the mode I stress intensity factor (K1) at the top 
% of a vertical crack under specified traction conditions. It uses a 
% discretized approach where the crack is divided into segments and the 
% contribution from each segment is summed.
%
% The calculation follows the methodology presented in:
% "Fluid-filled fractures in Earth's lithosphere: Gravitational loading, 
% interpenetration, and stable height of dikes and veins"
% by Townsend and Pollard (2018), Journal of Structural Geology.
%
% Arguments: (input)
%   tnFunc  - Function handle for normal traction distribution
%             Must accept a position argument z and return traction value
%   c       - Crack half-length [m]
%   mu      - Shear modulus [Pa]
%   nu      - Poisson's ratio [-]
%   z       - Array of positions along crack [-c to c] [m]
%   zmid    - Midpoints between z positions [m]
%   Precomp - Structure containing precomputed parameters from 
%             TownsendPollardPrecompute2018, must include fields:
%             .KIb1 - Precomputed stress intensity factor term 1
%             .KIb2 - Precomputed stress intensity factor term 2
%
% Arguments: (output)
%   K1Top   - Mode I stress intensity factor at top of crack [Pa*m^0.5]
%
% Notes:
%   - The function requires precomputed parameters generated by 
%     TownsendPollardPrecompute2018
%   - The crack is discretized into segments and the K1 contribution from
%     each segment is calculated using TownsendPollardPartialPressure_KSPEED
%   - Traction is evaluated at the midpoint of each segment
%
% Example usage:
%   c = 1;              % Crack half-length
%   mu = 1e9;           % Shear modulus
%   nu = 0.25;          % Poisson's ratio
%   tnFunc = @(z) 1e6;  % Constant traction
%   n = 50;             % Number of discretization points
%   Precomp = TownsendPollardPrecompute2018(c, n, nu);
%   K1Top = PollardTractionIntegrationVerticalCrackK(tnFunc, c, mu, nu, ...
%           Precomp.z, Precomp.zmid, Precomp);
%
% References:
%   Townsend, M.R., and Pollard, D.D., 2018, Fluid-filled fractures in
%   Earth's lithosphere: Gravitational loading, interpenetration, and
%   stable height of dikes and veins: Journal of Structural Geology,
%   v. 109, p. 38-54, doi:10.1016/j.jsg.2017.11.015
%
% See also: TownsendPollardPrecompute2018, TownsendPollardPartialPressure_KSPEED

    % Initialize K1 at top of crack
    K1Top = 0;
    
    % Loop through each segment of the discretized crack
    for j = 1:numel(zmid)
        % Calculate segment contribution to K1 using precomputed parameters
        % Evaluate traction at midpoint of current segment
        [K1TopSeg, ~] = TownsendPollardPartialPressure_KSPEED(...
            z(j+1), z(j), c, tnFunc((z(j)+z(j+1))/2), ...
            Precomp.KIb1(j), Precomp.KIb2(j));
        
        % Add segment contribution to total K1
        K1Top = K1Top + K1TopSeg;
    end
end